## Config for experiments

env: BabyAI-BossLevel-v0
wrapper: LanguageWrapper
wrapper_kwargs:
  max_len: 36
  pad: true

time_limit: 344

alg: BehaviorCloningForwardPrediction
alg_kwargs:
  dataset: datasets/BabyAIBossLevel_l36_50k_traj.pkl
  validation_dataset: datasets/BabyAIBossLevel_l36_50k_valid_traj.pkl
  dataset_fraction: 1.0
  batch_size: 32
  optim_kwargs:
    lr: 0.0001
    eps: 0.00000001
  action_coeff: 1.0
  forward_freq: 3
  forward_coeff: 0.7 # Change to run different experiments
  unsup_coeff: 0.0 # Change to run different experiments

train_kwargs:
  total_steps: 1000000
  log_freq: 100
  eval_ep: 50 # Run 50 evaluation episodes.
  eval_freq: 10000
  validation_metric: action_accuracy
  max_eval_steps: 50

network: DTForward
network_kwargs:
  n_layer: 4
  n_dec_layer: 1
  n_head: 2
  n_embd: 128
  mlp_ratio: 2
  block_size: 512
