## Config for Crafting BC IL experiment
env: omniglot
  
eval_env: null

alg: Reptile
alg_kwargs:
  optim_cls: ["import", "torch.optim", "Adam"]
  optim_kwargs:
    lr: 0.001
    eps: 0.00000001
  meta_optim_cls: ["import", "torch.optim", "SGD"]
  meta_optim_kwargs:
    lr: 0.1
    eps: 0.00000001
  num_support: 5
  num_query: 1
  batch_size: 5
  inner_iters: 1
  meta_batch_size: 1
  action_coeff: 1.0
  lang_coeff: 0.0
  random_coeff: False

train_kwargs:
  total_steps: 100000
  log_freq: 10
  eval_freq: 200
  validation_metric: query/action_loss
  use_eval_mode: False

network: OmniglotCNN
