## Config for Crafting BC IL experiment
env: mazebase-v0
env_kwargs:
  config: seen_full

eval_env: mazebase-v0
eval_env_kwargs:
  config: unseen_full

alg: BehaviorCloning
alg_kwargs:
  dataset: /shared/jhejna/ask-your-human/new_data/dataset_
  validation_dataset: /shared/jhejna/ask-your-human/valid_new_data/dataset_
  dataset_fraction: 1.0
  batch_size: 64
  optim_cls: ["import", "torch.optim", "AdamW"]
  optim_kwargs:
    lr: 0.0001
    eps: 0.00000001
    weight_decay: 0.05
  grad_norm: 1.0
  pretraining: False
  lang_coeff: 0.25
  unsup_coeff: 0.25
  unsup_ema_tau: 0.01
  unsup_ema_update_freq: 1

train_kwargs:
  total_steps: 325000
  log_freq: 100
  eval_ep: 200
  eval_freq: 2000
  validation_metric: accuracy
  use_eval_mode: False

network: ViT
network_kwargs:
  depth: 4
  num_heads: 2
  embed_dim: 128
  unsup_dim: 128
  mlp_ratio: 2
  decoder_layers: 1
  drop_rate: 0.1
  attn_drop_rate: 0.1
  drop_path_rate: 0.1
